### ISSUE TITLE
make the web app multi linugal

### ISSUE THREAD

**Issue by alex-rind** [fhstp/easynwk-web#83]

**Comment by julia221501** [comment]
https://www.positronx.io/vue-i18n-tutorial-how-to-build-multi-lingual-vue-js-app/

**Comment by alex-rind** [comment]
Summer 2023 progress: 
- Decision to use <https://vue-i18n.intlify.dev/guide/> 
- German and English language packs started by summer intern

**Comment by alex-rind** [comment]
solved in [v2.2.0](https://github.com/fhstp/easynwk-web/releases/tag/v2.2.0) ed402f02691ca1c1f2f736a086b03ae9034b7d18
